sonar.projectKey=ciberme-backend
sonar.projectName=CiberMe Backend
sonar.projectVersion=1.0

sonar.sources=app

sonar.python.version=3.12

sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.venv/**,**/venv/**,**/*.pyc

sonar.sourceEncoding=UTF-8
